type RoomReady {
  connectionId: String!
  gameServerHost: String!
  gameServerPort: Int!
  transactionId: String
}

# ---------------------------------------

# ---------------------------------------

type Subscription {
  roomReady: RoomReady
}
