export enum DailyBonusError {
  CONFIG_DAILY_BONUS_NOT_ACTIVE = 'CONFIG_DAILY_BONUS_NOT_ACTIVE',
  CONFIG_DAILY_BONUS_IS_EXPIRED = 'CONFIG_DAILY_BONUS_IS_EXPIRED',
  INVALID_DATA = 'INVALID_DATA',
  NOT_ENOUGH = 'NOT_ENOUGH',
}
