export enum EVENT_NAMES {
  TRANSITION_DONE = 'TRANSITION_DONE',
  TRANSITION_BEGIN = 'TRANSITION_BEGIN',
  TRANSITION_ERROR = 'TRANSITION_ERROR',
  TRANSITION_COMMIT = 'TRANSITION_COMMIT',
  TRANSITION_ROLLBACK = 'TRANSITION_ROLLBACK',
  JOIN_TO_SHOWCASE = 'JOIN_TO_SHOWCASE',
  UPLOAD_FILE_CREATE = 'UPLOAD_FILE_CREATE',
  USER_LOGIN_UPDATE = 'USER_LOGIN_UPDATE',
}
